// Code generated by "stringer -type=NodeColor"; DO NOT EDIT

package quadtree

import "fmt"

const _NodeColor_name = "Black"

var _NodeColor_index = [...]uint8{0, 5}

func (i NodeColor) String() string {
	if i >= NodeColor(len(_NodeColor_index)-1) {
		return fmt.Sprintf("NodeColor(%d)", i)
	}
	return _NodeColor_name[_NodeColor_index[i]:_NodeColor_index[i+1]]
}
