// Code generated by "stringer -type=QNodeColor"; DO NOT EDIT

package quadtree

import "fmt"

const _QNodeColor_name = "Black"

var _QNodeColor_index = [...]uint8{0, 5}

func (i QNodeColor) String() string {
	if i >= QNodeColor(len(_QNodeColor_index)-1) {
		return fmt.Sprintf("QNodeColor(%d)", i)
	}
	return _QNodeColor_name[_QNodeColor_index[i]:_QNodeColor_index[i+1]]
}
