// Code generated by "stringer -type=Quadrant"; DO NOT EDIT

package quadtree

import "fmt"

const _Quadrant_name = "NorthwestNortheastSouthwestSoutheastrootQuadrant"

var _Quadrant_index = [...]uint8{0, 9, 18, 27, 36, 48}

func (i Quadrant) String() string {
	if i < 0 || i >= Quadrant(len(_Quadrant_index)-1) {
		return fmt.Sprintf("Quadrant(%d)", i)
	}
	return _Quadrant_name[_Quadrant_index[i]:_Quadrant_index[i+1]]
}
