// Code generated by "stringer -type=Side"; DO NOT EDIT

package quadtree

import "fmt"

const _Side_name = "WestNorthEastSouth"

var _Side_index = [...]uint8{0, 4, 9, 13, 18}

func (i Side) String() string {
	if i < 0 || i >= Side(len(_Side_index)-1) {
		return fmt.Sprintf("Side(%d)", i)
	}
	return _Side_name[_Side_index[i]:_Side_index[i+1]]
}
