// Code generated by "stringer -type=side"; DO NOT EDIT

package quadtree

import "fmt"

const _side_name = "westnortheastsouth"

var _side_index = [...]uint8{0, 4, 9, 13, 18}

func (i side) String() string {
	if i < 0 || i >= side(len(_side_index)-1) {
		return fmt.Sprintf("side(%d)", i)
	}
	return _side_name[_side_index[i]:_side_index[i+1]]
}
